### ISSUE TITLE
TypeError at / wrong argument type Class (expected Module)

### ISSUE THREAD

**Issue by afaraldo** [zertico/zertico#13]
Hi, I need some help.
I am using rails 4.2.10 and I have installed the gem responders. I also have my separate application in engines.

**my application_controller.rb**
require "application_responder"

module System
  class ApplicationController < Zertico::Controller
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    respond_to :html, :json
    responders :flash, :http_cache
    self.responder = ApplicationResponder
  end
end

**my application_responder.rb**
class ApplicationResponder < ActionController::Responder
  include Responders::FlashResponder
  include Responders::HttpCacheResponder
  include Responders::CollectionResponder

  include Zertico::Responder **(this is where the error appears)**
end

**Comment by fernandes** [comment]
hi @afaraldo , this gem is not maintained anymore... I suggest you to use some gem that has a better support like http://trailblazer.to/ thank you!
